In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

# Array in numpy

In [4]:
a1 = np.array([1,2,3])
a1
# This is one dimensional array 

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3],
              [1.2,2.2,3.2]])
a2
# a2.shape to check the row and columnn 
# a2.ndim to check the dimension of the array 
# a2.size to see the size of an array 

array([[1. , 2. , 3. ],
       [1.2, 2.2, 3.2]])

In [7]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a3.ndim

3

In [10]:
a4 = np.array([[[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[13,14,15,16], [17,18,19,20], [21,22,23,24]]]])  # 4D
a4

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [11]:
a4.shape

(1, 2, 3, 4)

In [12]:
a4.ndim

4

In [13]:
a1.ndim,a2.ndim,a3.ndim,a4.ndim

(1, 2, 3, 4)

In [14]:
import pandas as pd 
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  1.2  2.2  3.2

## Creating Arrays 

In [15]:
ones =  np.ones((1,2,3,4), dtype=int)
ones

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]])

In [16]:
range_array = np.arange(0,10,2,int)
range_array

array([0, 2, 4, 6, 8])

In [17]:
# Random array
random_array  = np.random.randint(1,9,size=(2,2,3,5))
random_array

array([[[[1, 5, 1, 3, 3],
         [2, 3, 2, 3, 1],
         [2, 7, 1, 4, 4]],

        [[2, 1, 4, 6, 3],
         [1, 5, 4, 2, 1],
         [2, 6, 5, 7, 2]]],


       [[[6, 4, 2, 1, 2],
         [8, 2, 5, 2, 8],
         [7, 8, 2, 8, 4]],

        [[1, 6, 6, 1, 7],
         [6, 4, 6, 1, 4],
         [6, 3, 6, 5, 7]]]], dtype=int32)

Pseudo Random Number
A pseudorandom number generator (PRNG) is a type of pseudorandom number which produces sequence that can be used
in computations for generating true Random Numbers or Secure Entropy sources within the system where these
operations will take place. These are generally faster than truly randomly generated numbers because they have to
ensure all possible outcomes exist, but there's no guarantee them would occur at random times due to a large
number of possibilities and not necessarily in series from an initial seed (which is also called
non-deterministic)
## np.random.seed , shape, reshape 

In [18]:
range1 = np.arange(1,10,2)
range1

array([1, 3, 5, 7, 9])

A "seed" can be used as the starting point for generating pseudorandom numbers. There are many ways you could set
a 'seed' - it might start with a number, use current time or some other information that changes over time and
then produce an infinite series of random values if those factors were combined in this way (using bitwise
operations).


In [19]:
np.random.seed(42)
random_array1 = np.random.randint(10, size=(5,3))
random_array1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]], dtype=int32)

In [20]:
a4 = np.random.randint(10, size= (2,3,4,5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]], dtype=int32)

In statistics, "n-dimensional" means a vector with n components (size). In terms of computer science or data
analysis terminology like Pseudorandom Number Generators(PRNGs) which is also using 'random' in this context and
you are asking about it. A single dimension can be the number itself while multidimensional PRNGS could represent
a vector, matrix etc., all having different dimensions but still behaving as one entity when used with these
mathematical operations like summation or multiplication among others for instance because they use multiple
components to generate numbers in this way (multiple inputs).

In [21]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [22]:
a4.dtype

dtype('int32')

In [23]:
#get the first most number of inner arrays
a4[1:2,2:3,0:1,:5]

array([[[[4, 9, 6, 6, 8]]]], dtype=int32)

### Aggreegation

In [24]:
np.min(a2)

np.float64(1.0)

In [25]:
np.std(a2)

np.float64(0.8225975119502045)

In [26]:
np.var(a2)

np.float64(0.6766666666666669)

In [27]:
np.sum(a4)

np.int64(559)

In [28]:
sum(a4)

array([[[13,  9, 15,  5,  9],
        [10,  8, 16,  5, 15],
        [ 7, 11,  2, 13,  5],
        [10,  2,  8, 11, 12]],

       [[13, 16, 12,  9, 10],
        [ 9,  1, 15, 14, 16],
        [ 8,  3, 10, 11,  9],
        [ 2,  2,  7,  3,  7]],

       [[ 7, 10, 11, 11, 17],
        [12, 14,  3, 15,  1],
        [12,  6, 11, 12, 14],
        [10, 10,  3,  9,  8]]], dtype=int32)

In [29]:
%timeit np.sum(a4)

3.77 μs ± 256 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
%timeit sum(a4)

2.55 μs ± 65.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [31]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [32]:
high_var_array

array([   1,  100,  200,  300, 4000, 5000])

In [33]:
low_var_array

array([ 2,  4,  6,  8, 10])

In [34]:
# Means return the average of the array elements. The average is taken over the flattened array by default, otherwise the specific axis 
np.mean(high_var_array), np.mean(low_var_array)

(np.float64(1600.1666666666667), np.float64(6.0))

`%matplotlib inline` appears to be an alias inside Jupyter notebooks that directly plots the graphs within your
current cell (i.e., cells containing interactive widgets like buttons, text inputs or display outputs). Here's how
it works in a simple example of plotting using matplotlibthonwidgets

In [38]:
# np.linspace this is use for the linear space it create a equal point between the given range 

x =  np.linspace(-5,15,10, dtype=int)
x

array([-5, -3, -1,  1,  3,  6,  8, 10, 12, 15])

In [37]:
#np.identify in  this method it creates a matric where there is 1 in the diagonal and at other position there is 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Operations 

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [41]:
# scalar operation 

# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [42]:
# re3lation operation
a2>5 


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
# when we perform the task between two array that is called vector function
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

 ### Array Function

In [45]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
a1

array([[62., 30., 11.],
       [46., 22., 42.],
       [88., 32., 12.]])

In [ ]:
# min / max/ sum/ prod
# axis = 0  for columns
# axis = 1 for rows
np.max(a1,axis=1)

array([62., 46., 88.])

In [49]:
# mean / median / std / var
np.mean(a1),np.mean(a1, axis=1)

(np.float64(38.333333333333336),
 array([34.33333333, 36.66666667, 44.        ]))